#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "${DIR}/bash-theme.sh"
export PATH="${PATH}:${DIR}/../bin"

if [[ "${OSTYPE}" == "linux-gnu" ]]; then
	# Generic Linux Config
	alias open="xdg-open"

	alias pbcopy='xclip -selection clipboard'
	alias pbpaste='xclip -selection clipboard -o'

	alias pacman-remove-unused='sudo pacman -Rns $(sudo pacman -Qtdq)'
elif [[ "${OSTYPE}" == "linux-gnueabihf" ]]; then
	# Raspberry Pi Specific Config
	cputemp() {
		cpu=$(cat /sys/class/thermal/thermal_zone0/temp)
		echo "$((cpu / 100))" | sed -E "s/([[:digit:]]+)([[:digit:]])/temp=\1.\2'C/"
	}
	alias gputemp="vcgencmd measure_temp"
fi

alias ll="ls -al"
alias la="ls -a"

alias egrep="egrep --color=auto"

function reload() {
	# clear all aliases
	unalias -a

	if [[ $# -eq 0 ]]; then
		source ~/.bashrc
		return
	fi

	if [[ $1 != "--pull" ]]; then
		echo "Unknown flag $1"
		source ~/.bashrc
		return
	else
		echo "pulling"
	fi

	cd ~/.dotfiles
	orig="$(git stash list | wc -l)"
	git stash -u
	if [[ "$(git stash list | wc -l)" != "${orig}" ]]; then
		echo "Stashed uncommitted changes:"
		git stash show
	fi

	git checkout master
	git pull
	./init
	source ~/.bashrc
}

alias gits="git status"
alias gitd="git diff"
alias gitl="git log"
alias gitb="git branch"

alias wdiff="wdiff -n -w $'\033[30;41m' -x $'\033[0m' -y $'\033[30;42m' -z $'\033[0m'"

alias gen-ctags="ctags -R -f ./.git/tags ."

export CLICOLOR=1
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
export PATH="${PATH}:${HOME}/.dotfiles/bin"
export GOPATH="${HOME}/repos/go"
export PATH="${PATH}:${GOPATH}/bin"

export JQ_COLORS="1;37:0;39:0;39:0;39:0;32:1;39:1;39"

# enable Ctrl+S i-search
stty -ixon

