#!/usr/bin/env bash

set -e

DOTFILES_ROOT="${HOME}/.dotfiles"
cd "${DOTFILES_ROOT}"

source install/helpers

install/install
install/bootstrap

# Configure linux to use oh my zsh.  This should ALWAYS be the last thing in this file.
if [[ "$(uname)" = "Linux" ]]; then
	if [[ prompt "Do you want to restart?" ]]; then
		chsh -s `which zsh`
		sudo shutdown -r 0
	fi
fi

