#!/usr/bin/env bash
#
# Initializes a computer with packages, bootstraps everything.
# Supposed to be run to init a fresh computer.

set -e

DOTFILES_ROOT="${HOME}/.dotfiles"
cd "${DOTFILES_ROOT}"

source helpers.sh

trap 'err_report ${LINENO}' ERR

info 'installing dotfiles'

# Needs to be DOTFILES_ROOT to get fully qualified paths
for src in $(find -L "${DOTFILES_ROOT}" -name '*.symlink' | sort); do
	dst="${HOME}/.$(basename ${src%.*})"
	running "Linking $(basename ${dst})"
	lnx "${src}" "${dst}";
	ok
done

info "running bootstrapping scripts"

for strapper in $(find . -name bootstrap.sh | sort); do
	module "Running ${strapper#./}"
	$strapper
done

finished
