#!/usr/bin/env bash
#
# Initializes a computer with packages, bootstraps everything.
# Supposed to be run to init a fresh computer.

set -e

DOTFILES_ROOT="${HOME}/.dotfiles"
cd "${DOTFILES_ROOT}"

source helpers.sh

trap 'err_report ${LINENO}' ERR

header 'installing dotfiles'

for src in $(cat "./symlinks.txt"); do
	dst="${HOME}/.$(basename ${src})"
	running "Linking $(basename ${dst})"
	lnx "${DOTFILES_ROOT}/${src}" "${dst}"
	ok
done

log "running bootstrapping scripts"

for bootstrapper in $(find . -name bootstrap.sh | sort); do
	# Strip the leading ./ for a cleaner display
	header "Running ${bootstrapper#./}"
	"${bootstrapper}"
done

header "All done! No more bare bones for you."
