#!/usr/bin/env bash
#
# Installs dotfiles, does a lot of config stuff.

set -e

DOTFILES_ROOT="$(pwd)"

source install/helpers

trap 'err_report ${LINENO}' ERR

install_dotfiles() {
	info 'installing dotfiles'

	for src in $(find "${DOTFILES_ROOT}" -name '*.symlink' -not -path '*.git*' -not -path '*.backup*'); do
		dst="${HOME}/.$(basename ${src%.*})"
		running "Linking $(basename ${dst})"
		lnx "${src}" "${dst}"; ok
	done
}

install_dotfiles

info "locating supplementary bootstrapping scripts"
files=$(find . -name bootstrap.sh -not -path '*ubuntu*' -not -path '*macos*')

if [[ "$(uname)" = "Darwin" ]]; then
	running "Running macos/bootstrap.sh"
	macos/bootstrap.sh
else
	running "Running ubuntu/bootstrap.sh"
	ubuntu/bootstrap.sh
fi

for i in ${files[@]}; do
	running "Running ${i#./}"
	$i; ok
done

