#!/usr/bin/env bash
#
# Installs dotfiles, does a lot of config stuff.

set -e

DOTFILES_ROOT="$(pwd)"

source install/helpers

install_dotfiles() {
	info 'installing dotfiles'

	for src in $(find "${DOTFILES_ROOT}" -name '*.symlink' -not -path '*.git*'); do
		dst="${HOME}/.$(basename ${src%.*})"
		lnx "${src}" "${dst}"
	done
}

install_dotfiles

info "locating supplementary bootstrapping scripts"
files=$(find . -name bootstrap.sh)

info "running scripts..."
for i in ${files[@]}; do
	$i || failure "script $i did not run properly"
done

info "finished bootstrapping"

