#!/usr/bin/env bash
#
# Installs dotfiles, does a lot of config stuff.

set -e

DOTFILES_ROOT="$(pwd)"

source install/helpers

trap 'err_report ${LINENO}' ERR

install_dotfiles() {
	info 'installing dotfiles'

	for src in $(find "${DOTFILES_ROOT}" -name '*.symlink' -not -path '*.git*' -not -path '*.backup*'); do
		dst="${HOME}/.$(basename ${src%.*})"
		lnx "${src}" "${dst}"
	done
}

install_dotfiles

info "locating supplementary bootstrapping scripts"
files=$(find . -name bootstrap.sh)

for i in ${files[@]}; do
	running "Running ${i#./}"
	$i; ok
done

