#!/usr/bin/env bash
#
# A bunch of utility functions and variables

if [[ -z "${HELPERS_IMPORTED}" ]]; then

HELPERS_IMPORTED="true"

BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN_ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT_GRAY='\033[0;37m'
DARK_GRAY='\033[1;30m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHT_BLUE='\033[1;34m'
LIGHT_PURPLE='\033[1;35m'
LIGHT_CYAN='\033[1;36m'
WHITE='\033[1;37m'
NC='\033[0m'

success() {
	echo -e "${GREEN}✓ $1${NC}"
}

unsure() {
	echo -e "${BLUE}? $1${NC}"
}

failure() {
	echo -e "${RED}✖ $1${NC}"
}

warn () {
	echo -e "${YELLOW}⚠ $1${NC}"
}

info() {
	echo -e "${DARK_GRAY}  $1${NC}"
}

user() {
	echo -e "  $1"
}

# From: http://wiki.bash-hackers.org/snipplets/print_horizontal_line
divider() {
	printf '%*s' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
}


lnx() {
	target_file=$1
	link=$2
	name=$(basename "${link}")

	skip=false

	if [[ -e ${link} || -L ${link} ]]; then
		if [[ "$(readlink ${link})" = "${target_file}" ]]; then
			success "${link} already linked!"
			skip=true
		else

			overwrite=false
			user "File already exists: ${link} ($(basename "${target_file}")), what do you want to do?\n\
			[s]kip, [o]verwrite?"
			read -n 1 action
			case "$action" in
				o )
					overwrite=true;;
				s )
					skip=true;;
				* )
					warn "invalid input. Skipping"; skip=true;;
			esac

			echo

			if [[ ${overwrite} = "true" ]]; then
				rm -rf ${link}
				success "deleted old file"
			fi
		fi
	fi

	if [[ ${skip} != 'true' ]]; then
		ln -s ${target_file} ${link} && success "${name} linked successfully!"
	fi
}

prompt() {
	printf "$1\n"
	select yn in "Yes" "No"; do
		case $yn in
			Yes ) return 0;;
			No ) return 1;;
		esac
	done
}

fi # end HELPERS_IMPORTED

