#!/usr/bin/env bash
#
# Initializes a computer with packages, bootstraps everything.
# Supposed to be run to init a fresh computer.

set -e

DOTFILES_ROOT="${HOME}/.dotfiles"
cd "${DOTFILES_ROOT}"

source install/helpers

trap 'err_report ${LINENO}' ERR

if [[ $(uname) = "Darwin" ]]; then
	macos/packages.sh
else
	ubuntu/packages.sh
fi

install/bootstrap

# Configure linux to use oh my zsh.  This should ALWAYS be the last thing in this file.
if [[ "$(uname)" != "Darwin" ]]; then
	chsh -s $(which zsh)
	if prompt "Do you want to restart? (Required for everything to work properly)" ; then
		sudo shutdown -r 0
	fi
fi

