#!/usr/bin/env bash
#
# Installs packages

set -e

if [[ $(uname) = "Darwin" ]]; then
	macos/packages.sh
else
	ubuntu/packages.sh
fi

files=$(find . -name install.sh)

for i in "${files[@]}"; do
	i
done

